/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as PaymentSuccessRouteImport } from './routes/payment/success'
import { Route as PaymentFailedRouteImport } from './routes/payment/failed'
import { Route as DocumentsIdRouteImport } from './routes/documents/$id'
import { Route as CheckoutIdRouteImport } from './routes/checkout/$id'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiPaymentWebhookRouteImport } from './routes/api/payment/webhook'
import { Route as ApiPaymentCreateInvoiceRouteImport } from './routes/api/payment/create-invoice'
import { Route as ApiOrdersIdRouteImport } from './routes/api/orders/$id'
import { Route as ApiDownloadTokenRouteImport } from './routes/api/download/$token'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiAdminUploadRouteImport } from './routes/api/admin/upload'
import { Route as ApiAdminSheetsTestWriteRouteImport } from './routes/api/admin/sheets-test-write'
import { Route as ApiAdminGoogleStatusRouteImport } from './routes/api/admin/google-status'
import { Route as AdminAdminOrdersRouteImport } from './routes/_admin/admin/orders'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin/admin/dashboard'
import { Route as ApiAdminOrdersIndexRouteImport } from './routes/api/admin/orders/index'
import { Route as ApiAdminDocumentsIndexRouteImport } from './routes/api/admin/documents/index'
import { Route as ApiAdminDocumentsIdRouteImport } from './routes/api/admin/documents/$id'
import { Route as AdminAdminDocumentsNewRouteImport } from './routes/_admin/admin/documents/new'
import { Route as AdminAdminDocumentsIdEditRouteImport } from './routes/_admin/admin/documents/$id/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment/success',
  path: '/payment/success',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentFailedRoute = PaymentFailedRouteImport.update({
  id: '/payment/failed',
  path: '/payment/failed',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIdRoute = DocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutIdRoute = CheckoutIdRouteImport.update({
  id: '/checkout/$id',
  path: '/checkout/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentWebhookRoute = ApiPaymentWebhookRouteImport.update({
  id: '/api/payment/webhook',
  path: '/api/payment/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCreateInvoiceRoute = ApiPaymentCreateInvoiceRouteImport.update({
  id: '/api/payment/create-invoice',
  path: '/api/payment/create-invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersIdRoute = ApiOrdersIdRouteImport.update({
  id: '/api/orders/$id',
  path: '/api/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadTokenRoute = ApiDownloadTokenRouteImport.update({
  id: '/api/download/$token',
  path: '/api/download/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUploadRoute = ApiAdminUploadRouteImport.update({
  id: '/api/admin/upload',
  path: '/api/admin/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSheetsTestWriteRoute = ApiAdminSheetsTestWriteRouteImport.update({
  id: '/api/admin/sheets-test-write',
  path: '/api/admin/sheets-test-write',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminGoogleStatusRoute = ApiAdminGoogleStatusRouteImport.update({
  id: '/api/admin/google-status',
  path: '/api/admin/google-status',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminOrdersRoute = AdminAdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminOrdersIndexRoute = ApiAdminOrdersIndexRouteImport.update({
  id: '/api/admin/orders/',
  path: '/api/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDocumentsIndexRoute = ApiAdminDocumentsIndexRouteImport.update({
  id: '/api/admin/documents/',
  path: '/api/admin/documents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDocumentsIdRoute = ApiAdminDocumentsIdRouteImport.update({
  id: '/api/admin/documents/$id',
  path: '/api/admin/documents/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminDocumentsNewRoute = AdminAdminDocumentsNewRouteImport.update({
  id: '/admin/documents/new',
  path: '/admin/documents/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDocumentsIdEditRoute =
  AdminAdminDocumentsIdEditRouteImport.update({
    id: '/admin/documents/$id/edit',
    path: '/admin/documents/$id/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/api/admin/google-status': typeof ApiAdminGoogleStatusRoute
  '/api/admin/sheets-test-write': typeof ApiAdminSheetsTestWriteRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/payment/create-invoice': typeof ApiPaymentCreateInvoiceRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/admin/documents/new': typeof AdminAdminDocumentsNewRoute
  '/api/admin/documents/$id': typeof ApiAdminDocumentsIdRoute
  '/api/admin/documents/': typeof ApiAdminDocumentsIndexRoute
  '/api/admin/orders/': typeof ApiAdminOrdersIndexRoute
  '/admin/documents/$id/edit': typeof AdminAdminDocumentsIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/orders': typeof AdminAdminOrdersRoute
  '/api/admin/google-status': typeof ApiAdminGoogleStatusRoute
  '/api/admin/sheets-test-write': typeof ApiAdminSheetsTestWriteRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/payment/create-invoice': typeof ApiPaymentCreateInvoiceRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/admin/documents/new': typeof AdminAdminDocumentsNewRoute
  '/api/admin/documents/$id': typeof ApiAdminDocumentsIdRoute
  '/api/admin/documents': typeof ApiAdminDocumentsIndexRoute
  '/api/admin/orders': typeof ApiAdminOrdersIndexRoute
  '/admin/documents/$id/edit': typeof AdminAdminDocumentsIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/admin/login': typeof AdminLoginRoute
  '/checkout/$id': typeof CheckoutIdRoute
  '/documents/$id': typeof DocumentsIdRoute
  '/payment/failed': typeof PaymentFailedRoute
  '/payment/success': typeof PaymentSuccessRoute
  '/admin/': typeof AdminIndexRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/orders': typeof AdminAdminOrdersRoute
  '/api/admin/google-status': typeof ApiAdminGoogleStatusRoute
  '/api/admin/sheets-test-write': typeof ApiAdminSheetsTestWriteRoute
  '/api/admin/upload': typeof ApiAdminUploadRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/download/$token': typeof ApiDownloadTokenRoute
  '/api/orders/$id': typeof ApiOrdersIdRoute
  '/api/payment/create-invoice': typeof ApiPaymentCreateInvoiceRoute
  '/api/payment/webhook': typeof ApiPaymentWebhookRoute
  '/_admin/admin/documents/new': typeof AdminAdminDocumentsNewRoute
  '/api/admin/documents/$id': typeof ApiAdminDocumentsIdRoute
  '/api/admin/documents/': typeof ApiAdminDocumentsIndexRoute
  '/api/admin/orders/': typeof ApiAdminOrdersIndexRoute
  '/_admin/admin/documents/$id/edit': typeof AdminAdminDocumentsIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/checkout/$id'
    | '/documents/$id'
    | '/payment/failed'
    | '/payment/success'
    | '/admin/'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/api/admin/google-status'
    | '/api/admin/sheets-test-write'
    | '/api/admin/upload'
    | '/api/auth/$'
    | '/api/download/$token'
    | '/api/orders/$id'
    | '/api/payment/create-invoice'
    | '/api/payment/webhook'
    | '/admin/documents/new'
    | '/api/admin/documents/$id'
    | '/api/admin/documents/'
    | '/api/admin/orders/'
    | '/admin/documents/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/checkout/$id'
    | '/documents/$id'
    | '/payment/failed'
    | '/payment/success'
    | '/admin'
    | '/admin/dashboard'
    | '/admin/orders'
    | '/api/admin/google-status'
    | '/api/admin/sheets-test-write'
    | '/api/admin/upload'
    | '/api/auth/$'
    | '/api/download/$token'
    | '/api/orders/$id'
    | '/api/payment/create-invoice'
    | '/api/payment/webhook'
    | '/admin/documents/new'
    | '/api/admin/documents/$id'
    | '/api/admin/documents'
    | '/api/admin/orders'
    | '/admin/documents/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/privacy'
    | '/terms'
    | '/admin/login'
    | '/checkout/$id'
    | '/documents/$id'
    | '/payment/failed'
    | '/payment/success'
    | '/admin/'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/orders'
    | '/api/admin/google-status'
    | '/api/admin/sheets-test-write'
    | '/api/admin/upload'
    | '/api/auth/$'
    | '/api/download/$token'
    | '/api/orders/$id'
    | '/api/payment/create-invoice'
    | '/api/payment/webhook'
    | '/_admin/admin/documents/new'
    | '/api/admin/documents/$id'
    | '/api/admin/documents/'
    | '/api/admin/orders/'
    | '/_admin/admin/documents/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  CheckoutIdRoute: typeof CheckoutIdRoute
  DocumentsIdRoute: typeof DocumentsIdRoute
  PaymentFailedRoute: typeof PaymentFailedRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminGoogleStatusRoute: typeof ApiAdminGoogleStatusRoute
  ApiAdminSheetsTestWriteRoute: typeof ApiAdminSheetsTestWriteRoute
  ApiAdminUploadRoute: typeof ApiAdminUploadRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiDownloadTokenRoute: typeof ApiDownloadTokenRoute
  ApiOrdersIdRoute: typeof ApiOrdersIdRoute
  ApiPaymentCreateInvoiceRoute: typeof ApiPaymentCreateInvoiceRoute
  ApiPaymentWebhookRoute: typeof ApiPaymentWebhookRoute
  ApiAdminDocumentsIdRoute: typeof ApiAdminDocumentsIdRoute
  ApiAdminDocumentsIndexRoute: typeof ApiAdminDocumentsIndexRoute
  ApiAdminOrdersIndexRoute: typeof ApiAdminOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/success': {
      id: '/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment/failed': {
      id: '/payment/failed'
      path: '/payment/failed'
      fullPath: '/payment/failed'
      preLoaderRoute: typeof PaymentFailedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$id': {
      id: '/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$id': {
      id: '/checkout/$id'
      path: '/checkout/$id'
      fullPath: '/checkout/$id'
      preLoaderRoute: typeof CheckoutIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/webhook': {
      id: '/api/payment/webhook'
      path: '/api/payment/webhook'
      fullPath: '/api/payment/webhook'
      preLoaderRoute: typeof ApiPaymentWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/create-invoice': {
      id: '/api/payment/create-invoice'
      path: '/api/payment/create-invoice'
      fullPath: '/api/payment/create-invoice'
      preLoaderRoute: typeof ApiPaymentCreateInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders/$id': {
      id: '/api/orders/$id'
      path: '/api/orders/$id'
      fullPath: '/api/orders/$id'
      preLoaderRoute: typeof ApiOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/$token': {
      id: '/api/download/$token'
      path: '/api/download/$token'
      fullPath: '/api/download/$token'
      preLoaderRoute: typeof ApiDownloadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/upload': {
      id: '/api/admin/upload'
      path: '/api/admin/upload'
      fullPath: '/api/admin/upload'
      preLoaderRoute: typeof ApiAdminUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/sheets-test-write': {
      id: '/api/admin/sheets-test-write'
      path: '/api/admin/sheets-test-write'
      fullPath: '/api/admin/sheets-test-write'
      preLoaderRoute: typeof ApiAdminSheetsTestWriteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/google-status': {
      id: '/api/admin/google-status'
      path: '/api/admin/google-status'
      fullPath: '/api/admin/google-status'
      preLoaderRoute: typeof ApiAdminGoogleStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/orders': {
      id: '/_admin/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminAdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/orders/': {
      id: '/api/admin/orders/'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders/'
      preLoaderRoute: typeof ApiAdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/documents/': {
      id: '/api/admin/documents/'
      path: '/api/admin/documents'
      fullPath: '/api/admin/documents/'
      preLoaderRoute: typeof ApiAdminDocumentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/documents/$id': {
      id: '/api/admin/documents/$id'
      path: '/api/admin/documents/$id'
      fullPath: '/api/admin/documents/$id'
      preLoaderRoute: typeof ApiAdminDocumentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/documents/new': {
      id: '/_admin/admin/documents/new'
      path: '/admin/documents/new'
      fullPath: '/admin/documents/new'
      preLoaderRoute: typeof AdminAdminDocumentsNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/documents/$id/edit': {
      id: '/_admin/admin/documents/$id/edit'
      path: '/admin/documents/$id/edit'
      fullPath: '/admin/documents/$id/edit'
      preLoaderRoute: typeof AdminAdminDocumentsIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminOrdersRoute: typeof AdminAdminOrdersRoute
  AdminAdminDocumentsNewRoute: typeof AdminAdminDocumentsNewRoute
  AdminAdminDocumentsIdEditRoute: typeof AdminAdminDocumentsIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminOrdersRoute: AdminAdminOrdersRoute,
  AdminAdminDocumentsNewRoute: AdminAdminDocumentsNewRoute,
  AdminAdminDocumentsIdEditRoute: AdminAdminDocumentsIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
  AdminLoginRoute: AdminLoginRoute,
  CheckoutIdRoute: CheckoutIdRoute,
  DocumentsIdRoute: DocumentsIdRoute,
  PaymentFailedRoute: PaymentFailedRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminGoogleStatusRoute: ApiAdminGoogleStatusRoute,
  ApiAdminSheetsTestWriteRoute: ApiAdminSheetsTestWriteRoute,
  ApiAdminUploadRoute: ApiAdminUploadRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiDownloadTokenRoute: ApiDownloadTokenRoute,
  ApiOrdersIdRoute: ApiOrdersIdRoute,
  ApiPaymentCreateInvoiceRoute: ApiPaymentCreateInvoiceRoute,
  ApiPaymentWebhookRoute: ApiPaymentWebhookRoute,
  ApiAdminDocumentsIdRoute: ApiAdminDocumentsIdRoute,
  ApiAdminDocumentsIndexRoute: ApiAdminDocumentsIndexRoute,
  ApiAdminOrdersIndexRoute: ApiAdminOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
